### ISSUE TITLE
Korrekturassistent, ein Tutor darf die Namen nicht sehen

### ISSUE THREAD

**Issue by tilluhlig** [ostepu/ostepu-core#272]
sollte über die neue Einstellung verwaltet werden, ob der Tutor diese sehen darf, ansonsten muss etwas anderes angezeigt werden

**Comment by tilluhlig** [comment]
Im Korrekturassistenten soll die IDs der Korrekturaufträge auch angezeigt werden (der Korrekturauftrag eines Tutors hat immer entsprechende IDs), die er auch in seinem Korrekturarchiv hat.

**Comment by Garados007** [comment]
Abgeschlossen, wenn MarkingTool2 übernommen wird. Die Namen werden jetzt nie angezeigt.

**Comment by tilluhlig** [comment]
Aber ein Dozent und ein Admin sollen die Namen natürlich sehen können.

**Comment by Garados007** [comment]
Tut mir leid, dass ich mich falsch ausgedrückt habe. Ich meine natürlich, dass bei einem Tutor die Namen nie angezeigt werden, ansonsten bleibt alles bei dem Alten. Dozenten und Admins können die Namen weiterhin sehen.
