### ISSUE TITLE
Zulassungsbedingungen, Schwellwert anzeigen

### ISSUE THREAD

**Issue by Garados007** [ostepu/ostepu-core#288]
Neben der Eingabe der Prozentschwellwerte die Anzahl der Punkte anzeigen, die dafür nötig ist.

**Comment by tilluhlig** [comment]
![page_admin_condition_setd_de](https://cloud.githubusercontent.com/assets/7592615/23137986/544d60aa-f7a5-11e6-8b9a-c7eb07a4a2d2.png)
